import React from 'react';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="pb-4 border-b border-gray-200 dark:border-slate-700">
        <h1 className="text-3xl font-bold text-slate-800 dark:text-slate-100">Terms and Conditions</h1>
        <p className="mt-1 text-lg text-slate-500 dark:text-slate-400">Last updated: July 29, 2024</p>
      </div>
      <div className="bg-white p-8 rounded-lg border border-slate-200 dark:bg-slate-800 dark:border-slate-700 space-y-6 max-w-4xl mx-auto text-slate-600 dark:text-slate-300 leading-relaxed prose prose-slate dark:prose-invert">
        
        <p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the Muvikit website (the "Service") operated by Muvikit Technologies ("us", "we", or "our").</p>
        
        <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>

        <section>
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">1. Acceptance of Terms</h2>
          <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">2. Description of Service</h2>
          <p>Muvikit provides a collection of free online tools and utilities for various purposes, including but not limited to file conversion, image editing, financial calculations, and text analysis. While we strive for accuracy, we do not guarantee the correctness, reliability, or suitability of any information or result generated by our tools. The Service is provided on an "AS IS" and "AS AVAILABLE" basis.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">3. User Conduct and Responsibilities</h2>
          <p>You agree to use the Service only for lawful and ethical purposes. You are solely responsible for any data, documents, or images you upload or process through our tools. You must not use Muvikit for any of the following:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Engaging in any activity that is illegal, fraudulent, or harmful.</li>
            <li>Uploading or processing content that infringes on any third party's intellectual property rights.</li>
            <li>Attempting to disrupt or compromise the integrity or security of the Service.</li>
            <li>Using automated systems, such as "bots" or "spiders," to access the Service in a manner that sends more request messages to our servers than a human can reasonably produce in the same period.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">4. Data Privacy and Security</h2>
          <p>We take your privacy seriously. Most of our tools operate entirely on the client-side, meaning your files and data are processed directly in your browser and are never sent to or stored on our servers. For tools that require server-side processing or AI analysis:</p>
           <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Data is transmitted securely.</li>
            <li>Uploaded files and data are only used for the one-time purpose of providing the requested service and are not stored permanently.</li>
            <li>We do not share, sell, or view your private data.</li>
          </ul>
           <p>For more details, please review our Privacy Policy (if available).</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">5. Intellectual Property</h2>
          <p>All content, branding, logos, code, and design on the Service are the exclusive property of Muvikit Technologies and are protected by copyright, trademark, and other intellectual property laws. You may not copy, reproduce, modify, or distribute any part of our Service without our express written permission.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">6. Limitation of Liability</h2>
          <p>In no event shall Muvikit Technologies, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">7. Changes to Terms</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">8. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at:</p>
          <p><a href="mailto:MuvikitTechnologies@gmail.com" className="text-[var(--theme-primary)] hover:underline dark:text-sky-400">MuvikitTechnologies@gmail.com</a></p>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;